/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _DT_BINDINGS_CLK_MT6768_VDECSYS_H
#define _DT_BINDINGS_CLK_MT6768_VDECSYS_H

#define CLK_VDEC_CKEN			0
#define CLK_VDEC_ACTIVE			1
#define CLK_VDEC_CKEN_ENG		2
#define CLK_VDEC_LARB1_CKEN		3
#define CLK_VDEC_NR_CLK			4

#endif /* _DT_BINDINGS_CLK_MT6768_VDECSYS_H */
